# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverb',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
