# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20161123_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=20)),
                ('question_4', models.CharField(max_length=20)),
                ('question_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='A2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=20)),
                ('question_4', models.CharField(max_length=20)),
                ('question_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=20)),
                ('question_4', models.CharField(max_length=20)),
                ('question_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='B2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=20)),
                ('question_4', models.CharField(max_length=20)),
                ('question_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='C1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=20)),
                ('question_4', models.CharField(max_length=20)),
                ('question_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Adverb',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
