# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20161129_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=2)),
                ('question_1', models.CharField(max_length=100)),
                ('question_2', models.CharField(max_length=100)),
                ('question_3', models.CharField(max_length=100)),
                ('question_4', models.CharField(max_length=100)),
                ('question_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='A1',
        ),
        migrations.DeleteModel(
            name='A2',
        ),
        migrations.DeleteModel(
            name='B1',
        ),
        migrations.DeleteModel(
            name='B2',
        ),
        migrations.DeleteModel(
            name='C1',
        ),
    ]
