# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_filledopenquestion_multiplechoice_openquestion_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserScore',
        ),
    ]
