# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20170106_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='totalCorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='totalIncorrect',
            field=models.IntegerField(default=0),
        ),
    ]
